on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - run:
         ./mill all __.compile + __.test
